language: python
sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true
    - python : "3.8-dev"
      dist: xenial
      sudo: true

install:
  - pip install pipenv
  - make develop

script:
  - make check

after_success:
  - coveralls
