environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -U setuptools pip virtualenv pipenv"
  - "%PYTHON%\\python.exe -m pipenv sync --dev"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pipenv run pytest tests --junitxml=report.xml"

on_finish:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile(
        "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)",
        (Resolve-Path .\report.xml))
